# Puerto MQTT
listener 1883
listener 9001


allow_anonymous true
protocol websockets

max_inflight_messages 100
max_queued_messages 100

# Para clean_session=False
persistence true
persistence_location /mosquitto/data